services:
  dns-proxy:
    build: .
    container_name: dns-proxy
    restart: always
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./sing-box:/etc/sing-box
      - ./mosdns:/etc/mosdns