services:
  dns-proxy:
    build: .
    container_name: dns-proxy
    restart: always
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "1080:1080/tcp"
    volumes:
      - ./sing-box:/etc/sing-box
      - ./mosdns:/etc/mosdns