log:
  level: info
  file: "/var/log/mosdns.log"

api:
  http: "0.0.0.0:9091"

# include 的插件会比本配置文件中的插件先初始化。
include: []

plugins:
  # 国内域名
  - tag: geosite_cn
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/geosite-cn.txt"
        - "/etc/mosdns/rules/direct-list.txt"

  # 国外域名
  - tag: geosite_no_cn
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/geosite-geolocation-!cn.txt"
        - "/etc/mosdns/rules/geosite-all@!cn.txt"
        - "/etc/mosdns/rules/proxy-list.txt"
        - "/etc/mosdns/rules/gfw.txt"

  # CDN域名
  - tag: geosite_cdn_cn
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/geosite-all@cn.txt"

  # 国内IP
  - tag: geoip_cn
    type: ip_set
    args:
      files:
        - "/etc/mosdns/rules/cn_all.txt"

  # NTP域名
  - tag: ntp
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/ntp_domains.txt"

  # 防DNS泄漏检测
  - tag: hosts
    type: hosts
    args:
      files:
        - "/etc/mosdns/hosts.txt"

  # 广告域名
  - tag: adlist
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rules/reject-list.txt"
        - "/etc/mosdns/rules/anti-ad-domains.txt"
        - "/etc/mosdns/rules/AWAvenue-Ads-Rule-Mosdns_v5.txt"
        - "/etc/mosdns/rules/mosdns_adrules.txt"

  # PTR 黑名单
  - tag: local_ptr
    type: domain_set
    args:
      files:
        - "/etc/mosdns/local-ptr.txt"

  # 国内DNS服务器
  - tag: forward_local
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: AliDNS_DoH
          addr: https://dns.alidns.com/dns-query
          bootstrap: "223.5.5.5"
        - tag: DNSPod_DoH
          addr: https://doh.pub/dns-query
          bootstrap: "119.29.29.29"
        - tag: 360DNS_DoH
          addr: https://doh.360.cn/dns-query
          bootstrap: "101.226.4.6"
        - tag: 114_Primary
          addr: 114.114.114.114
        - tag: 114_Secondary
          addr: 114.114.115.115
        - tag: CNNIC_Primary
          addr: 1.2.4.8
        - tag: CNNIC_Secondary
          addr: 210.2.4.8
        - tag: Baidu
          addr: 180.76.76.76

  # 国外DNS服务器（sing-box代理）
  - tag: forward_remote
    type: forward
    args:
      concurrent: 3
      upstreams:
        - tag: google_DoH
          addr: https://dns.google/dns-query
          bootstrap: "8.8.8.8"
          socks5: "127.0.0.1:2080"
        - tag: cloudflare_DoH
          addr: https://dns.cloudflare.com/dns-query
          bootstrap: "1.0.0.1"
          socks5: "127.0.0.1:2080"
        - tag: ibm_DoH
          addr: https://dns.quad9.net/dns-query
          bootstrap: "9.9.9.9"
          socks5: "127.0.0.1:2080"
        - tag: cisco_DoH
          addr: https://dns.opendns.com/dns-query
          bootstrap: "208.67.222.222"
          socks5: "127.0.0.1:2080"
        - tag: yandex_DoH
          addr: https://common.dot.dns.yandex.net
          bootstrap: "77.88.8.8"
          socks5: "127.0.0.1:2080"

   # DNS缓存
  - tag: cache
    type: cache
    args:
      size: 8192 # 增大缓存容量
      lazy_cache_ttl: 10800 # 3小时(单位:秒)
      dump_file: "/etc/mosdns/cache.dump"
      dump_interval: 600

  # 不修改TTL
  - tag: no_modify_ttl
    type: sequence
    args:
      - exec: ttl 0-0

    # 修改TTL
  - tag: modify_ttl
    type: sequence
    args:
      - exec: ttl 30-60

  # 有响应终止返回
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches: qname $geosite_cdn_cn
        exec: $modify_ttl
      - matches: "!qname $geosite_cdn_cn"
        exec: $no_modify_ttl
      - matches: has_resp
        exec: accept

  # ipset操作 - 添加到国内ipset集合
  - tag: ipset_cn
    type: sequence
    args:
      - exec: ipset cn_ip_set,inet,24 cn_ip_set6,inet6,48

  # ipset操作 - 添加到国外pset集合
  - tag: ipset_no_cn
    type: sequence
    args:
      - exec: ipset no_cn_ip_set,inet,24 no_cn_ip_set6,inet6,48

  # 国内ECS处理器
  - tag: ecs_cn
    type: ecs_handler
    args:
      preset: "1.2.4.8"
      send: false
      forward: false

  # 国外ECS处理器
  - tag: ecs_no_cn
    type: ecs_handler
    args:
      preset: "204.13.154.3"
      send: false
      forward: false

  # 国内解析
  - tag: local_sequence
    type: sequence
    args:
      - exec: $ecs_cn
      - exec: $forward_local
      - exec: $ipset_cn

  # 国外解析
  - tag: remote_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $ecs_no_cn
      - exec: $forward_remote
      - exec: $ipset_no_cn

  # 检查IP是否为非国内IP，国外IP，则丢弃响应，触发fallback机制使用国外DNS重新解析
  - tag: query_is_no_local_ip
    type: sequence
    args:
      - exec: $ecs_cn
      - exec: $forward_local
      - matches:
          - "!resp_ip $geoip_cn"
      - exec: drop_resp
  
  # fallback机制 - 未匹配域名的回滚机制
  - tag: fallback
    type: fallback
    args:
      primary: query_is_no_local_ip
      secondary: remote_sequence
      threshold: 500
      always_standby: true

  # fallback机制 - 未匹配域名的回滚机制
  - tag: cdn_fallback
    type: fallback
    args:
      primary: query_is_no_local_ip
      secondary: local_sequence
      threshold: 100
      always_standby: true

  # 查询国内域名
  - tag: query_is_local_domain
    type: sequence
    args:
      - matches: qname $geosite_cn
        exec: $local_sequence

  # 查询国外域名
  - tag: query_is_no_local_domain
    type: sequence
    args:
      - matches: qname $geosite_no_cn
        exec: $remote_sequence

  # 查询CDN域名
  - tag: query_is_cdn_domain
    type: sequence
    args:
      - matches: qname $geosite_cdn_cn
        exec: $cdn_fallback

  # 拒绝广告域名和特定查询类型
  - tag: query_is_reject
    type: sequence
    args:
      - matches:
          - qname $adlist
        exec: reject 3
      - matches:
          - qtype 12
          - qname $local_ptr
        exec: reject 3
      - matches:
          - qtype 65
        exec: reject 3

  # 主要处理序列
  - tag: main_sequence
    type: sequence
    args:
      # 广告屏蔽
      - exec: $query_is_reject
      # NTP域名 - 始终使用国内DNS解析
      - matches:
          - qname $ntp
        exec: $local_sequence
      - exec: jump has_resp_sequence
      # 首先检查 hosts 文件
      - exec: $hosts
      - exec: jump has_resp_sequence
      # 对除NTP、国外CDN域名、广告域名、本地PTR以外的查询使用缓存
      - matches:
          - "!qname $ntp"
          - "!qname $geosite_cdn_cn"
          - "!qname $adlist"
          - "!qname $local_ptr"
        exec: $cache
      # CDN域名
      - exec: $query_is_cdn_domain
      - exec: jump has_resp_sequence
      # 中国域名
      - exec: $query_is_local_domain
      - exec: jump has_resp_sequence
      # 非中国域名
      - exec: $query_is_no_local_domain
      - exec: jump has_resp_sequence
      # 未匹配域名
      - exec: $fallback

  # 启动监听服务
  - tag: udp_server
    type: udp_server
    args:
      entry: main_sequence
      listen: ":53"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main_sequence
      listen: ":53"
